version: 2.1

orbs:
  maven: circleci/maven@1.4.1

shared: &shared
  steps:
    - checkout
    - restore_cache:
        keys:
          - sortgraphql-cache-{{ checksum "pom.xml" }}
          - sortgraphql-cache- # fallback in case previous cache key is not found
    - run: mvn clean verify -Dmaven.javadoc.skip=true -Dinvoker.skip=true -DskipPitest=true -B -V
    - save_cache:
        paths:
          - ~/.m2
        key: sortgraphql-cache--{{ checksum "pom.xml" }}

jobs:
  jdk17:
    docker:
      - image: cimg/openjdk:21.0
    <<: *shared
  jdk18:
    docker:
      - image: cimg/openjdk:21.0
    <<: *shared
  jdk11:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - sortgraphql-cache-{{ checksum "pom.xml" }}
            - sortgraphql-cache- # fallback in case previous cache key is not found
      - run: mvn clean verify -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -B -V
      - run: mvn clean jacoco:prepare-agent integration-test jacoco:report -B
      - run: mvn coveralls:report -B -DrepoToken=$COVERALLS_REPO_TOKEN
      - run: mvn sonar:sonar -Dsonar.projectKey=Ekryd_sortgraphql -Dsonar.organization=ekryd-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      - save_cache:
          paths:
            - ~/.m2
          key: sortgraphql-cache--{{ checksum "pom.xml" }}

workflows:
  version: 2
  work:
    jobs:
      - jdk17
      - jdk18:
          requires:
            - jdk17
      - jdk11:
          filters: # using regex filters requires the entire branch to match
            branches:
              only: # only branches matching the below regex filters will run
                - master
          requires:
            - jdk17
            - jdk18
        
